# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from vtk.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.loadButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadButton.setObjectName("loadButton")
        self.verticalLayout.addWidget(self.loadButton)
        self.thresholdSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.thresholdSpinBox.setMinimum(0)
        self.thresholdSpinBox.setMaximum(255)
        self.thresholdSpinBox.setProperty("value", 100)
        self.thresholdSpinBox.setObjectName("thresholdSpinBox")
        self.verticalLayout.addWidget(self.thresholdSpinBox)
        self.segmentButton = QtWidgets.QPushButton(self.centralwidget)
        self.segmentButton.setObjectName("segmentButton")
        self.verticalLayout.addWidget(self.segmentButton)
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)
        self.vtkWidget = QtWidgets.QWidget(self.centralwidget)
        self.vtkWidget.setObjectName("vtkWidget")
        self.verticalLayout.addWidget(self.vtkWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "3D Medical Image Reconstruction"))
        self.loadButton.setText(_translate("MainWindow", "Load DICOM Series"))
        self.segmentButton.setText(_translate("MainWindow", "Segment Image"))
        self.saveButton.setText(_translate("MainWindow", "Save Model"))